export const FACTION_PFUNC = {
    ADD_MEMBER: 'addMember',
    KICK_MEMBER: 'kickMember',
    SET_CHARACTER_RANK: 'setCharacterRank',
    ADD_BANK: 'addBank',
    SUB_BANK: 'subBank',
    ADD_RANK: 'addRank',
    REMOVE_RANK: 'removeRank',
    SET_RANK_NAME: 'setRankName',
    SET_RANK_PERMISSIONS: 'setRankPermissions',
    SET_RANK_WEIGHT: 'setRankWeight',
    SET_HEAD_QUARTERS: 'setHeadQuarters',
    SET_BLIP: 'setBlip',
    SWAP_RANKS: 'swapRanks',
    ADD_PARKING_SPOT: 'addParkingSpot',
    REMOVE_PARKING_SPOT: 'removeParkingSpot',
    PURCHASE_VEHICLE: `purchaseVehicle`,
    TOGGLE_VEHICLE_RANK_PERMISSION: `toggleVehicleRankPermission`,
    SPAWN_VEHICLE: `spawnVehicle`,
};
