import { LOCALE_CLOTHING } from '../../shared/locales';
import { CLOTHING_STORE_PAGE } from '../../shared/enums';

export const EXAMPLE_CLOTHING_DATA = [
    {
        pageName: LOCALE_CLOTHING.LABEL_HAT,
        drawables: [66],
        ids: [0],
        internalID: CLOTHING_STORE_PAGE.HATS,
        isProp: true,
        maxDrawables: [163],
        maxTextures: [1],
        textures: [0],
        startValue: 0,
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_MASK,
        drawables: [1],
        ids: [1],
        internalID: CLOTHING_STORE_PAGE.MASK,
        isProp: false,
        maxDrawables: [197],
        maxTextures: [4],
        textures: [0],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_SHIRT,
        names: [LOCALE_CLOTHING.LABEL_TOP, LOCALE_CLOTHING.LABEL_UNDERSHIRT, LOCALE_CLOTHING.LABEL_TORSO],
        drawables: [105, 15, 15],
        ids: [11, 8, 3],
        internalID: CLOTHING_STORE_PAGE.SHIRT,
        isProp: false,
        maxDrawables: [392, 188, 196],
        maxTextures: [1, 1, 1],
        textures: [0, 0, 0],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_BOTTOMS,
        drawables: [14],
        ids: [4],
        internalID: 3,
        isProp: false,
        maxDrawables: [143],
        maxTextures: [16],

        textures: [0],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_SHOES,
        drawables: [59],
        ids: [6],
        internalID: CLOTHING_STORE_PAGE.SHOES,
        isProp: false,
        maxDrawables: [101],
        maxTextures: [26],
        textures: [0],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_GLASSES,
        drawables: [-1],
        ids: [1],
        internalID: CLOTHING_STORE_PAGE.GLASSES,
        isProp: true,
        maxDrawables: [39],
        maxTextures: [0],
        textures: [-1],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_EARRINGS,
        drawables: [-1],
        ids: [2],
        internalID: CLOTHING_STORE_PAGE.EARRINGS,
        isProp: true,
        maxDrawables: [40],
        maxTextures: [0],
        textures: [-1],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_BAG,
        drawables: [0],
        ids: [5],
        internalID: CLOTHING_STORE_PAGE.BAG,
        isProp: false,
        maxDrawables: [99],
        maxTextures: [1],
        textures: [0],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_ARMOUR,
        drawables: [0],
        ids: [9],
        internalID: CLOTHING_STORE_PAGE.ARMOUR,
        isProp: false,
        maxDrawables: [16],
        maxTextures: [1],
        textures: [0],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_WATCH,
        drawables: [-1],
        ids: [6],
        internalID: CLOTHING_STORE_PAGE.WATCH,
        isProp: true,
        maxDrawables: [40],
        maxTextures: [0],
        textures: [-1],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_BRACELET,
        drawables: [-1],
        ids: [7],
        internalID: CLOTHING_STORE_PAGE.BRACELET,
        isProp: true,
        maxDrawables: [8],
        maxTextures: [0],
        textures: [-1],
    },
    {
        pageName: LOCALE_CLOTHING.LABEL_ACCESSORY,
        drawables: [0],
        ids: [7],
        internalID: CLOTHING_STORE_PAGE.ACCESSORY,
        isProp: false,
        maxDrawables: [151],
        maxTextures: [1],
        textures: [0],
    },
];
