//@ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY CONTENTS

import { shallowRef } from 'vue'

import Atm from '../../../src/core/plugins/core-atm/webview/Atm.vue';
import CharacterCreator from '../../../src/core/plugins/core-character-creator/webview/CharacterCreator.vue';
import CharacterSelect from '../../../src/core/plugins/core-character-select/webview/CharacterSelect.vue';
import Clothing from '../../../src/core/plugins/core-clothing/webview/Clothing.vue';
import Dealership from '../../../src/core/plugins/core-dealership/webview/Dealership.vue';
import Factions from '../../../src/core/plugins/core-factions/webview/Factions.vue';
import Garage from '../../../src/core/plugins/core-garage/webview/Garage.vue';
import Hud from '../../../src/core/plugins/core-hud/webview/Hud.vue';
import PaintShop from '../../../src/core/plugins/core-paintshop/webview/PaintShop.vue';

export const PLUGIN_IMPORTS = {
    Atm: shallowRef(Atm),
    CharacterCreator: shallowRef(CharacterCreator),
    CharacterSelect: shallowRef(CharacterSelect),
    Clothing: shallowRef(Clothing),
    Dealership: shallowRef(Dealership),
    Factions: shallowRef(Factions),
    Garage: shallowRef(Garage),
    Hud: shallowRef(Hud),
    PaintShop: shallowRef(PaintShop),
};
