export const exampleEquipment = [
    {
        name: 'Bottoms',
        description: '',
        icon: 'bottoms',
        slot: 3,
        quantity: 1,
        behavior: 13,
        data: {
            startValue: 14,
            drawables: [15],
            ids: [4],
            textures: [2],
            isProp: false,
            sex: 1,
            dlcHashes: [0],
        },
        equipment: 3,
    },
    {
        name: 'Wrist Bracelet',
        description: '',
        icon: 'bracelet',
        slot: 10,
        quantity: 1,
        behavior: 13,
        data: {
            startValue: -1,
            drawables: [1],
            ids: [7],
            textures: [0],
            isProp: true,
            sex: 1,
            dlcHashes: [0],
        },
        equipment: 10,
    },
    {
        name: 'Glasses',
        description: '',
        icon: 'glasses',
        slot: 5,
        quantity: 1,
        behavior: 13,
        data: {
            startValue: -1,
            drawables: [1],
            ids: [1],
            textures: [255],
            isProp: true,
            sex: 1,
            dlcHashes: [0],
        },
        equipment: 5,
    },
    {
        name: 'stupid shirt',
        description: 'stupid',
        icon: 'shirt',
        slot: 2,
        quantity: 1,
        behavior: 13,
        data: {
            startValue: 392,
            drawables: [19, 2, 2],
            ids: [11, 8, 3],
            textures: [1, 0, 0],
            isProp: false,
            sex: 1,
            dlcHashes: [618336290, 2398078303, 0],
        },
        equipment: 2,
    },
    {
        name: 'dunce',
        description: 'dunce',
        icon: 'hat',
        slot: 0,
        quantity: 1,
        behavior: 13,
        data: {
            startValue: 0,
            drawables: [1],
            ids: [0],
            textures: [0],
            isProp: true,
            sex: 1,
            dlcHashes: [0],
        },
        equipment: 0,
    },
    {
        name: 'loafers',
        description: 'loafers',
        icon: 'shoes',
        slot: 4,
        quantity: 1,
        behavior: 13,
        data: {
            startValue: 34,
            drawables: [3],
            ids: [6],
            textures: [0],
            isProp: false,
            sex: 1,
            dlcHashes: [228479499],
        },
        equipment: 4,
    },
];
