export enum HUD_COMPONENT {
    HEALTH = 'health',
    ARMOUR = 'armour',
    CASH = 'cash',
    BANK = 'bank',
    TIME = 'time',
    WATER = 'water',
    FOOD = 'food',
    DEAD = 'dead',
    IDENTIFIER = 'identifier',
    MICROPHONE = 'microphone',
    INTERACTIONS = 'interactions',
    IS_IN_VEHICLE = 'isInVehicle',
    SEATBELT = 'seatbelt',
    SPEED = 'speed',
    GEAR = 'gear',
    ENGINE = 'engine',
    LOCK = 'lock',
    METRIC = 'isMetric',
    FUEL = 'fuel',
}
