export enum WORLD_WEATHER {
    CLEAR = 'CLEAR',
    EXTRA_SUNNY = 'EXTRASUNNY',
    CLOUDS = 'CLOUDS',
    OVERCAST = 'OVERCAST',
    RAIN = 'RAIN',
    CLEARING = 'CLEARING',
    THUNDER = 'THUNDER',
    SMOG = 'SMOG',
    FOGGY = 'FOGGY',
    XMAS = 'XMAS',
    SNOWLIGHT = 'SNOWLIGHT',
    BLIZZARD = 'BLIZZARD',
}
