export const eyebrowNames = [
    'Balanced',
    'Fashion',
    'Cleopatra',
    'Quizzical',
    'Femme',
    'Seductive',
    'Pinched',
    'Chola',
    'Triomphe',
    'Carefree',
    'Curvaceous',
    'Rodent',
    'Double Tram',
    'Thin',
    'Penciled',
    'Mother Plucker',
    'Straight and Narrow',
    'Natural',
    'Fuzzy',
    'Unkempt',
    'Caterpillar',
    'Regular',
    'Mediterranean',
    'Groomed',
    'Bushels',
    'Feathered',
    'Prickly',
    'Monobrow',
    'Winged',
    'Triple Tram',
    'Arched Tram',
    'Cutouts',
    'Fade Away',
    'Solo Tram',
    'None',
];
