export const facialHairNames = [
    'Stubble',
    'Balbo',
    'Circle Beard',
    'Goatee',
    'Chin',
    'Chin Fuzz',
    'Pencil Chin Strap',
    'Scruffy',
    'Musketeer',
    'Mustache',
    'Trimmed Beard',
    'Stubble Beard',
    'Thin Circle Beard',
    'Horseshoe',
    'Pencil and Chops',
    'Chin Strap',
    'Balbo and Sideburns',
    'Mutton Chops',
    'Scruffy Beard',
    'Curly',
    'Curly and Beard',
    'Handlebar',
    'Faustic',
    'Otto and Patch',
    'Otto and Beard',
    'Light Franz',
    'The Hampstead',
    'The Ambrose',
    'Lincoln Curtain',
    'Clean Shaven',
];
