export const makeup = [
    {
        name: 'Makeup',
        id: 4,
        labels: [
            'Smoky Black',
            'Bronze',
            'Soft Gray',
            'Retro Glam',
            'Natural Look',
            'Cat Eyes',
            'Chola',
            'Vamp',
            'Vinewood Glamour',
            'Bubblegum',
            'Aqua Dream',
            'Pin up',
            'Purple Passion',
            'Smoky Cat Eye',
            'Smoldering Ruby',
            'Pop Princess',
            'Kiss My Axe',
            'Panda Pussy',
            'The Bat',
            'Skull in Scarlet',
            'Serpentine',
            'The Veldt',
            'Unknown 1',
            'Unknown 2',
            'Unknown 3',
            'Unknown 4',
            'Tribal Lines',
            'Tribal Swirls',
            'Tribal Orange',
            'Tribal Red',
            'Trapped in A Box',
            'Clowning',
            'Guyliner',
            'Unknown 5',
            'Blood Tears',
            'Heavy Metal',
            'Sorrow',
            'Prince of Darkness',
            'Rocker',
            'Goth',
            'Punk',
            'Devastated',
        ],
    },
    {
        name: 'Blush',
        id: 5,
        labels: [
            //
            'Full',
            'Angled',
            'Round',
            'Horizontal',
            'High',
            'Sweetheart',
            'Eighties',
        ],
    },
    {
        name: 'Lipstick',
        id: 8,
        labels: [
            'Color Matte',
            'Color Gloss',
            'Lined Matte',
            'Lined Gloss',
            'Heavy Lined Matte',
            'Heavy Lined Gloss',
            'Lined Nude Matte',
            'Liner Nude Gloss',
            'Smudged',
            'Geisha',
        ],
    },
];
