export const VehicleClasses = {
    boat: 'boat',
    speedboat: 'speedboat',
    commercial: 'commercial',
    compact: 'compact',
    coupe: 'coupe',
    cycle: 'cycle',
    emergency: 'emergency',
    industrial: 'industrial',
    military: 'military',
    motorcycle: 'motorcycle',
    muscle: 'muscle',
    offroad: 'offroad',
    aircraft: 'aircraft',
    suv: 'suv',
    sedan: 'sedan',
    service: 'service',
    sport: 'sport',
    sportclassic: 'sportclassic',
    super: 'super',
    trailer: 'trailer',
    train: 'train',
    utility: 'utility',
    van: 'van'
};
