export interface Weapon {
    hash: number;
    name: string;
    desc?: string;
    type?: string;
    price?: number;
    clip?: number;
    stats?: {
        damage?: number;
        rate?: number;
        accuracy?: number;
        range?: number;
    };
    overall?: number;
    icon?: string;
}

const WeaponList: { [key: string]: Weapon } = {
    advancedrifle: {
        hash: 2937143193,
        name: 'Advanced Rifle',
        desc: 'The most lightweight and compact of all assault rifles, without compromising accuracy and rate of fire.',
        type: 'Assault Rifle',
        price: 14250,
        clip: 30,
        stats: {
            damage: 24,
            rate: 70,
            accuracy: 50,
            range: 45,
        },
        overall: 47.8,
        icon: 'advancedrifle',
    },
    appistol: {
        hash: 584646201,
        name: 'AP Pistol',
        desc: 'High-penetration, fully-automatic pistol. Holds 18 rounds in magazine with option to extend to 36 rounds.',
        type: 'Handgun',
        price: 5000,
        clip: 18,
        stats: {
            damage: 26,
            rate: 80,
            accuracy: 35,
            range: 30,
        },
        overall: 38.2,
        icon: 'appistol',
    },
    assaultrifle: {
        hash: 3220176749,
        name: 'Assault Rifle',
        desc: 'This standard assault rifle boasts a large capacity magazine and long distance accuracy.',
        type: 'Assault Rifle',
        price: 8550,
        clip: 30,
        stats: {
            damage: 30,
            rate: 60,
            accuracy: 45,
            range: 45,
        },
        overall: 44,
        icon: 'assaultrifle',
    },
    assaultriflemk2: {
        hash: 961495388,
        name: 'Assault Rifle MK II',
        desc: 'The definitive revision of an all-time classic: all it takes is a little work, and looks can kill after all.',
        type: 'Assault Rifle',
        price: 98750,
        clip: 30,
        stats: {
            damage: 33,
            rate: 60,
            accuracy: 45,
            range: 45,
        },
        overall: 44.6,
        icon: 'assaultriflemk2',
    },
    assaultshotgun: {
        hash: 3800352039,
        name: 'Assault Shotgun',
        desc: 'Fully automatic shotgun with 8 round magazine and high rate of fire.',
        type: 'Shotgun',
        price: 10000,
        clip: 8,
        stats: {
            damage: 77,
            rate: 50,
            accuracy: 25,
            range: 15,
        },
        overall: 35.4,
        icon: 'assaultshotgun',
    },
    assaultsmg: {
        hash: 4024951519,
        name: 'Assault SMG',
        desc: 'A high-capacity submachine gun that is both compact and lightweight. Holds up to 30 bullets in one magazine.',
        type: 'Machine Gun',
        price: 12550,
        clip: 30,
        stats: {
            damage: 23,
            rate: 55,
            accuracy: 45,
            range: 40,
        },
        overall: 40.6,
        icon: 'assaultsmg',
    },
    autoshotgun: {
        hash: 317205821,
        name: 'Auto Shotgun',
        desc: 'Fully automatic shotgun with 8 round magazine and high rate of fire.',
        type: 'Shotgun',
        price: 10000,
        clip: 8,
        stats: {
            damage: 77,
            rate: 50,
            accuracy: 25,
            range: 15,
        },
        overall: 35.4,
        icon: 'autoshotgun',
    },
    ball: {
        hash: 600439132,
        name: 'Baseball',
        desc: 'Come and get ya hotdog $5!',
        type: 'Thrown',
        price: 10,
        clip: 1,
        stats: {
            damage: 0,
            rate: 10,
            accuracy: 10,
            range: 0,
        },
        overall: 5,
        icon: 'ball',
    },
    bat: {
        hash: 2508868239,
        name: 'Baseball Bat',
        desc: 'Aluminum baseball bat with leather grip. Lightweight yet powerful for all you big hitters out there.',
        type: 'Melee',
        price: 100,
        stats: {
            damage: 20,
            rate: 10,
            range: 1,
        },
        overall: 10.33,
        icon: 'bat',
    },
    battleaxe: {
        hash: 3441901897,
        name: 'Battle Axe',
        desc: "If it's good enough for medieval foot soldiers, modern border guards and pushy soccer moms, it's good enough for you.",
        type: 'Melee',
        price: 300,
        stats: {
            damage: 15,
            rate: 15,
            range: 0,
        },
        overall: 10,
        icon: 'battleaxe',
    },
    bottle: {
        hash: 4192643659,
        name: 'Broken Bottle',
        desc: "It's not clever and it's not pretty but, most of the time, neither is the guy coming at you with a knife. When all else fails, this gets the job done.",
        type: 'Melee',
        price: 8,
        stats: {
            damage: 20,
            rate: 15,
            range: 1,
        },
        overall: 12,
        icon: 'bottle',
    },
    bullpuprifle: {
        hash: 2132975508,
        name: 'Bullpup Rifle',
        desc: 'The latest Chinese import taking America by storm, this rifle is known for its balanced handling. Lightweight and very controllable in automatic fire.',
        type: 'Assault Rifle',
        price: 14500,
        clip: 30,
        stats: {
            damage: 32,
            rate: 70,
            accuracy: 45,
            range: 45,
        },
        overall: 46,
        icon: 'bullpuprifle',
    },
    bullpupriflemk2: {
        hash: 2228681469,
        name: 'Bullpup Rifle MK II',
        desc: "So precise, so exquisite, it's not so much a hail of bullets as a symphony.",
        type: 'Assault Rifle',
        price: 14500,
        clip: 30,
        stats: {
            damage: 35,
            rate: 72,
            accuracy: 45,
            range: 45,
        },
        overall: 47.4,
        icon: 'bullpupriflemk2',
    },
    bullpupshotgun: {
        hash: 2640438543,
        name: 'Bullpup Shotgun',
        desc: 'More than makes up for its slow, pump-action rate of fire with its range and spread. Decimates anything in its projectile path.',
        type: 'Shotgun',
        price: 8000,
        clip: 14,
        stats: {
            damage: 67,
            rate: 20,
            accuracy: 30,
            range: 20,
        },
        overall: 31.4,
        icon: 'bullpupshotgun',
    },
    bzgas: {
        hash: 2694266206,
        name: 'Tear Gas',
        desc: 'Tear gas grenade, particularly effective at incapacitating multiple assailants. Sustained exposure can be lethal.',
        type: 'Thrown',
        price: 150,
        clip: 25,
        stats: {
            damage: 10,
            rate: 20,
            accuracy: 10,
            range: 15,
        },
        overall: 13.75,
        icon: 'bzgas',
    },
    carbinerifle: {
        hash: 2210333304,
        name: 'Carbine Rifle',
        desc: 'Combining long distance accuracy with a high capacity magazine, the Carbine Rifle can be relied on to make the hit.',
        type: 'Assault Rifle',
        price: 13000,
        clip: 30,
        stats: {
            damage: 32,
            rate: 65,
            accuracy: 55,
            range: 45,
        },
        overall: 47.4,
        icon: 'carbinerifle',
    },
    carbineriflemk2: {
        hash: 4208062921,
        name: 'Carbine Rifle MK II',
        desc: "This is bespoke, artisan firepower: you couldn't deliver a hail of bullets with more love and care if you inserted them by hand.",
        type: 'Assault Rifle',
        price: 107500,
        clip: 30,
        stats: {
            damage: 36,
            rate: 65,
            accuracy: 55,
            range: 45,
        },
        overall: 48.2,
        icon: 'carbineriflemk2',
    },
    ceramicpistol: {
        hash: 727643628,
        name: 'Ceramic Pistol',
        desc: "Not your grandma's ceramics. Although this pint-sized pistol is small enough to fit into her purse and won't set off a metal detector.",
        type: 'Handgun',
        price: 20000,
        clip: 12,
        stats: {
            damage: 32,
            rate: 44,
            accuracy: 36,
            range: 20,
        },
        overall: 27.6,
        icon: 'ceramicpistol',
    },
    combatmg: {
        hash: 2144741730,
        name: 'Combat MG',
        desc: 'Lightweight, compact machine gun that combines excellent maneuverability with a high rate of fire to devastating effect.',
        type: 'Machine Gun',
        price: 14800,
        clip: 100,
        stats: {
            damage: 55,
            rate: 65,
            accuracy: 45,
            range: 60,
        },
        overall: 59,
        icon: 'combatmg',
    },
    combatmgmk2: {
        hash: 3686625920,
        name: 'Combat MG MKII',
        desc: 'You can never have too much of a good thing: after all, if the first shot counts, then the next hundred or so must count for double.',
        type: 'Machine Gun',
        price: 119000,
        clip: 100,
        stats: {
            damage: 57,
            rate: 65,
            accuracy: 45,
            range: 60,
        },
        overall: 59.4,
        icon: 'combatmgmk2',
    },
    combatpdw: {
        hash: 171789620,
        name: 'Combat PDW',
        desc: "Who said personal weaponry couldn't be worthy of military personnel? Thanks to our lobbyists, not Congress. Integral suppressor.",
        type: 'Machine Gun',
        price: 11750,
        clip: 30,
        stats: {
            damage: 25,
            rate: 50,
            accuracy: 45,
            range: 38,
        },
        overall: 39.6,
        icon: 'combatpdw',
    },
    combatpistol: {
        hash: 1593441988,
        name: 'Combat Pistol',
        desc: 'A compact, lightweight semi-automatic pistol designed for law enforcement and personal defense use. 12-round magazine with option to extend to 16 rounds.',
        type: 'Handgun',
        price: 3200,
        clip: 12,
        stats: {
            damage: 27,
            rate: 40,
            accuracy: 50,
            range: 30,
        },
        overall: 31.4,
        icon: 'combatpistol',
    },
    compactlauncher: {
        hash: 125959754,
        name: 'Compact Grenade Launcher',
        desc: 'Focus groups using the regular model suggested it was too accurate and found it awkward to use with one hand on the throttle. Easy fix.',
        type: 'Heavy Weapon',
        price: 45000,
        clip: 1,
        stats: {
            damage: 95,
            rate: 10,
            accuracy: 15,
            range: 55,
        },
        overall: 39,
        icon: 'compactlauncher',
    },
    compactrifle: {
        hash: 1649403952,
        name: 'Compact Rifle',
        desc: 'Half the size, all the power, double the recoil: there\'s no riskier way to say "I\'m compensating for something".',
        type: 'Assault Rifle',
        price: 14650,
        clip: 30,
        stats: {
            damage: 36,
            rate: 60,
            accuracy: 35,
            range: 45,
        },
        overall: 43.2,
        icon: 'compactrifle',
    },
    crowbar: {
        hash: 2227010557,
        name: 'Crowbar',
        desc: 'Heavy-duty crowbar forged from high quality, tempered steel for that extra leverage you need to get the job done.',
        type: 'Melee',
        price: 55,
        stats: {
            damage: 10,
            rate: 15,
            range: 1,
        },
        overall: 8.67,
        icon: 'crowbar',
    },
    dagger: {
        hash: 2460120199,
        name: 'Antique Cavalry Dagger',
        desc: "You've been rocking the pirate-chic look for a while, but no vicious weapon to complete the look? Get this dagger with guarded hilt.",
        type: 'Melee',
        price: 2000,
        stats: {
            damage: 20,
            rate: 20,
            range: 2,
        },
        overall: 14,
        icon: 'dagger',
    },
    dbshotgun: {
        hash: 4019527611,
        name: 'Double Barrel Shotgun',
        desc: 'Do one thing, do it well. Who needs a high rate of fire when your first shot turns the other guy into a fine mist?',
        type: 'Shotgun',
        price: 15450,
        clip: 2,
        stats: {
            damage: 98,
            rate: 25,
            accuracy: 15,
            range: 10,
        },
        overall: 30,
        icon: 'dbshotgun',
    },
    doubleaction: {
        hash: 2548703416,
        name: 'Double Action Revolver',
        desc: 'Because sometimes revenge is a dish best served six times, in quick succession, right between the eyes.',
        type: 'Handgun',
        price: 75000,
        clip: 6,
        stats: {
            damage: 70,
            rate: 35,
            accuracy: 65,
            range: 20,
        },
        overall: 39.2,
        icon: 'doubleaction',
    },
    fireextinguisher: {
        hash: 101631238,
        name: 'Fire Extinguisher',
        desc: 'Smother the flames of your enemies.',
        type: 'Utility',
        price: 200,
        clip: 100,
        icon: 'fireextinguisher',
    },
    firework: {
        hash: 2138347493,
        name: 'Firework Launcher',
        desc: 'Put the flair back in flare with this firework launcher, guaranteed to raise some oohs and aahs from the crowd.',
        type: 'Heavy Weapon',
        price: 65000,
        clip: 1,
        stats: {
            damage: 45,
            rate: 5,
            accuracy: 12,
            range: 60,
        },
        overall: 26.4,
        icon: 'firework',
    },
    flare: {
        hash: 1233104067,
        name: 'Flare',
        desc: 'Signal some assistance.',
        type: 'Thrown',
        price: 50,
        clip: 1,
        stats: {
            damage: 0,
            rate: 10,
            accuracy: 10,
            range: 25,
        },
        overall: 11.25,
        icon: 'flare',
    },
    flaregun: {
        hash: 1198879012,
        name: 'Flare Gun',
        desc: 'Use to signal distress or drunken excitement. Warning: pointing directly at individuals may cause spontaneous combustion.',
        type: 'Handgun',
        price: 3750,
        clip: 1,
        stats: {
            damage: 20,
            rate: 10,
            accuracy: 30,
            range: 10,
        },
        overall: 16,
        icon: 'flaregun',
    },
    flashlight: {
        hash: 2343591895,
        name: 'Flashlight',
        desc: 'Intensify your fear of the dark with this short range, battery-powered light source. Handy for blunt force trauma.',
        type: 'Melee',
        price: 250,
        stats: {
            damage: 10,
            rate: 15,
            range: 0,
        },
        overall: 8.33,
        icon: 'flashlight',
    },
    golfclub: {
        hash: 1141786504,
        name: 'Golf Club',
        desc: 'Standard length, mid iron golf club with rubber grip for a lethal short game.',
        type: 'Melee',
        price: 125,
        stats: {
            damage: 20,
            rate: 10,
            range: 1,
        },
        overall: 10.33,
        icon: 'golfclub',
    },
    grenade: {
        hash: 2481070269,
        name: 'Grenade',
        desc: 'Standard fragmentation grenade. Pull pin, throw, then find cover. Ideal for eliminating clustered assailants.',
        type: 'Heavy Weapon',
        price: 2500,
        clip: 1,
        stats: {
            damage: 95,
            rate: 20,
            accuracy: 10,
            range: 15,
        },
        overall: 35,
        icon: 'grenade',
    },
    grenadelauncher: {
        hash: 2726580491,
        name: 'Grenade Launcher',
        desc: 'A compact, lightweight grenade launcher with semi-automatic functionality. Holds up to 10 rounds.',
        type: 'Heavy Weapon',
        price: 32400,
        clip: 10,
        stats: {
            damage: 95,
            rate: 20,
            accuracy: 10,
            range: 50,
        },
        overall: 39,
        icon: 'grenadelauncher',
    },
    smokelauncher: {
        hash: 1305664598,
        name: 'Smoke Launcher',
        desc: 'A compact, lightweight smoke launcher with semi-automatic functionality. Holds up to 10 rounds.',
        type: 'Utility',
        price: 4200,
        clip: 10,
        icon: 'smokelauncher',
    },
    gusenberg: {
        hash: 1627465347,
        name: 'Gusenberg Sweeper',
        desc: 'Complete your look with a Prohibition gun. Looks great being fired from an Albany Roosevelt or paired with a pinstripe suit.',
        type: 'Machine Gun',
        price: 14600,
        clip: 30,
        stats: {
            damage: 34,
            rate: 65,
            accuracy: 38,
            range: 56,
        },
        overall: 46.6,
        icon: 'gusenberg',
    },
    hammer: {
        hash: 1317494643,
        name: 'Hammer',
        desc: 'A robust, multi-purpose hammer with wooden handle and curved claw, this old classic still nails the competition.',
        type: 'Melee',
        price: 500,
        stats: {
            damage: 10,
            rate: 15,
            range: 1,
        },
        overall: 8.67,
        icon: 'hammer',
    },
    hatchet: {
        hash: 4191993645,
        name: 'Hatchet',
        desc: 'Add a good old-fashioned hatchet to your armory, and always have a back up for when ammo is hard to come by.',
        type: 'Melee',
        price: 750,
        stats: {
            damage: 15,
            rate: 15,
            range: 0,
        },
        overall: 10,
        icon: 'hatchet',
    },
    hazardcan: {
        hash: 3126027122,
        name: 'Hazard Can',
        desc: 'No idea what this is.',
        type: 'Thrown',
        price: 100,
        clip: 100,
        stats: {
            damage: 0,
            rate: 10,
            accuracy: 30,
            range: 1,
        },
        overall: 24.2,
        icon: 'hazardcan',
    },
    heavypistol: {
        hash: 3523564046,
        name: 'Heavy Pistol',
        desc: 'The heavyweight champion of the magazine fed, semi-automatic handgun world. Delivers accuracy and a serious forearm workout every time.',
        type: 'Handgun',
        price: 3750,
        clip: 18,
        stats: {
            damage: 40,
            rate: 40,
            accuracy: 50,
            range: 35,
        },
        overall: 37,
        icon: 'heavypistol',
    },
    heavyshotgun: {
        hash: 984333226,
        name: 'Heavy Shotgun',
        desc: 'The weapon to reach for when you absolutely need to make a horrible mess of the room. Best used near easy-wipe surfaces only.',
        type: 'Shotgun',
        price: 13550,
        clip: 6,
        stats: {
            damage: 85,
            rate: 45,
            accuracy: 30,
            range: 25,
        },
        overall: 38.6,
        icon: 'heavyshotgun',
    },
    heavysniper: {
        hash: 205991906,
        name: 'Heavy Sniper',
        desc: 'Features armor-piercing rounds for heavy damage. Comes with laser scope as standard.',
        type: 'Sniper Rifle',
        price: 38150,
        clip: 6,
        stats: {
            damage: 98,
            rate: 20,
            accuracy: 90,
            range: 100,
        },
        overall: 62.6,
        icon: 'heavysniper',
    },
    heavysnipermk2: {
        hash: 177293209,
        name: 'Heavy Sniper MK II',
        desc: "Far away, yet always intimate: if you're looking for a secure foundation for that long-distance relationship, this is it.",
        type: 'Sniper Rifle',
        price: 165375,
        clip: 6,
        stats: {
            damage: 98,
            rate: 20,
            accuracy: 90,
            range: 100,
        },
        overall: 62.6,
        icon: 'heavysnipermk2',
    },
    hominglauncher: {
        hash: 1672152130,
        name: 'Homing Launcher',
        desc: 'Infrared guided fire-and-forget missile launcher. For all your moving target needs.',
        type: 'Heavy Weapon',
        price: 165000,
        clip: 1,
        stats: {
            damage: 95,
            rate: 5,
            accuracy: 25,
            range: 75,
        },
        overall: 42,
        icon: 'hominglauncher',
    },
    knife: {
        hash: 2578778090,
        name: 'Knife',
        desc: 'This carbon steel 7" bladed knife is dual edged with a serrated spine to provide improved stabbing and thrusting capabilities.',
        type: 'Melee',
        price: 400,
        stats: {
            damage: 15,
            rate: 20,
            range: 1,
        },
        overall: 12,
        icon: 'knife',
    },
    knuckle: {
        hash: 3638508604,
        name: 'Knuckle Dusters',
        desc: 'Perfect for knocking out gold teeth, or as a gift to the trophy partner who has everything.',
        type: 'Melee',
        price: 7500,
        stats: {
            damage: 10,
            rate: 20,
            range: 1,
        },
        overall: 1,
        icon: 'knuckle',
    },
    machete: {
        hash: 3713923289,
        name: 'Machete',
        desc: "America's West African arms trade isn't just about giving. Rediscover the simple life with this rusty cleaver.",
        type: 'Melee',
        price: 8900,
        stats: {
            damage: 15,
            rate: 15,
            range: 0,
        },
        overall: 10,
        icon: 'machete',
    },
    machinepistol: {
        hash: 3675956304,
        name: 'Machine Pistol',
        desc: 'This fully automatic is the snare drum to your twin-engine V8 bass: no drive-by sounds quite right without it.',
        type: 'Machine Gun',
        price: 6250,
        clip: 12,
        stats: {
            damage: 28,
            rate: 70,
            accuracy: 40,
            range: 30,
        },
        overall: 36,
        icon: 'machinepistol',
    },
    marksmanpistol: {
        hash: 3696079510,
        name: 'Marksman Pistol',
        desc: "Not for the risk averse. Make it count as you'll be reloading as much as you shoot.",
        type: 'Handgun',
        price: 4350,
        clip: 1,
        stats: {
            damage: 80,
            rate: 15,
            accuracy: 30,
            range: 35,
        },
        overall: 32.4,
        icon: 'marksmanpistol',
    },
    marksmanrifle: {
        hash: 3342088282,
        name: 'Marksman Rifle',
        desc: "Whether you're up close or a disconcertingly long way away, this weapon will get the job done. A multi-range tool for tools.",
        type: 'Sniper Rifle',
        price: 15750,
        clip: 8,
        stats: {
            damage: 70,
            rate: 40,
            accuracy: 80,
            range: 90,
        },
        overall: 58,
        icon: 'marksmanrifle',
    },
    marksmanriflemk2: {
        hash: 1785463520,
        name: 'Marksman Rifle MK II',
        desc: 'Known in military circles as The Dislocator, this mod set will destroy both the target and your shoulder, in that order.',
        type: 'Sniper Rifle',
        price: 149000,
        clip: 8,
        stats: {
            damage: 70,
            rate: 40,
            accuracy: 80,
            range: 90,
        },
        overall: 58,
        icon: 'marksmanriflemk2',
    },
    mg: {
        hash: 2634544996,
        name: 'MG',
        desc: 'General purpose machine gun that combines rugged design with dependable performance. Long range penetrative power. Very effective against large groups.',
        type: 'Machine Gun',
        price: 13500,
        clip: 54,
        stats: {
            damage: 50,
            rate: 60,
            accuracy: 40,
            range: 60,
        },
        overall: 52,
        icon: 'mg',
    },
    microsmg: {
        hash: 324215364,
        name: 'Micro SMG',
        desc: 'Combines compact design with a high rate of fire at approximately 700-900 rounds per minute.',
        type: 'Machine Gun',
        price: 3750,
        clip: 16,
        stats: {
            damage: 21,
            rate: 60,
            accuracy: 30,
            range: 25,
        },
        overall: 31.2,
        icon: 'microsmg',
    },
    minigun: {
        hash: 1119849093,
        name: 'Minigun',
        desc: 'A devastating 6-barrel machine gun that features Gatling-style rotating barrels. Very high rate of fire (2000 to 6000 rounds per minute).',
        type: 'Heavy Weapon',
        price: 470000,
        clip: 595,
        stats: {
            damage: 30,
            rate: 100,
            accuracy: 40,
            range: 55,
        },
        overall: 63,
        icon: 'minigun',
    },
    minismg: {
        hash: 3173288789,
        name: 'Mini SMG',
        desc: 'Increasingly popular since the marketing team looked beyond spec ops units and started caring about the little guys in low income areas.',
        type: 'Machine Gun',
        price: 8900,
        clip: 20,
        stats: {
            damage: 22,
            rate: 84,
            accuracy: 33,
            range: 30,
        },
        overall: 36.2,
        icon: 'minismg',
    },
    molotov: {
        hash: 615608432,
        name: 'Molotov',
        desc: 'Crude yet highly effective incendiary weapon. No happy hour with this cocktail.',
        type: 'Thrown',
        price: 200,
        clip: 1,
        stats: {
            damage: 50,
            rate: 20,
            accuracy: 20,
            range: 8,
        },
        overall: 24.5,
        icon: 'molotov',
    },
    musket: {
        hash: 2828843422,
        name: 'Musket',
        desc: 'Armed with nothing but muskets and a superiority complex, the Brits took over half the world. Own the gun that built an Empire.',
        type: 'Shotgun',
        price: 21400,
        clip: 1,
        stats: {
            damage: 97,
            rate: 10,
            accuracy: 65,
            range: 85,
        },
        overall: 53.4,
        icon: 'musket',
    },
    navyrevolver: {
        hash: 2441047180,
        name: 'Navy Revolver',
        desc: 'A true museum piece. You want to know how the West was won - slow reload speeds and a whole heap of bloodshed.',
        type: 'Handgun',
        price: 55000,
        stats: {
            damage: 70,
            rate: 25,
            accuracy: 60,
            range: 35,
        },
        overall: 40,
        icon: 'navyrevolver',
    },
    nightstick: {
        hash: 1737195953,
        name: 'Nightstick',
        desc: '24" polycarbonate side-handled nightstick.',
        type: 'Melee',
        price: 400,
        stats: {
            damage: 10,
            rate: 15,
            range: 1,
        },
        overall: 8.67,
        icon: 'nightstick',
    },
    parachute: {
        hash: 4222310262,
        name: 'Parachute',
        desc: 'Suicidal tendencies interrupted by parachuttal tendencies.',
        type: 'Utility',
        price: 250,
        icon: 'parachute',
    },
    jerrycan: {
        hash: 883325847,
        name: 'Jerry Can',
        desc: 'Leaves a trail of gasoline that can be ignited.',
        type: 'Thrown',
        price: 100,
        clip: 100,
        stats: {
            damage: 0,
            rate: 10,
            accuracy: 30,
            range: 1,
        },
        overall: 24.2,
        icon: 'jerrycan',
    },
    pipebomb: {
        hash: 3125143736,
        name: 'Pipebomb',
        desc: "Remember, it doesn't count as an IED when you buy it in a store and use it in a first world country.",
        type: 'Heavy Weapon',
        price: 50000,
        clip: 10,
        stats: {
            damage: 85,
            rate: 10,
            accuracy: 35,
            range: 15,
        },
        overall: 36.25,
        icon: 'pipebomb',
    },
    pipewrench: {
        hash: 419712736,
        name: 'Pipe Wrench',
        desc: 'Perennial favourite of apocalyptic survivalists and violent fathers the world over, apparently it also doubles as some kind of tool.',
        type: 'Melee',
        price: 7150,
        stats: {
            damage: 10,
            rate: 15,
            range: 0,
        },
        overall: 8.33,
        icon: 'pipewrench',
    },
    pistol: {
        hash: 453432689,
        name: 'Pistol',
        desc: 'Standard handgun. A .45 caliber combat pistol with a magazine capacity of 12 rounds that can be extended to 16.',
        type: 'Handgun',
        price: 2500,
        clip: 12,
        stats: {
            damage: 26,
            rate: 40,
            accuracy: 40,
            range: 25,
        },
        overall: 28.2,
        icon: 'pistol',
    },
    pistol50: {
        hash: 2578377531,
        name: 'Pistol .50',
        desc: 'High-impact pistol that delivers immense power but with extremely strong recoil. Holds 9 rounds in magazine.',
        type: 'Handgun',
        price: 3900,
        clip: 9,
        stats: {
            damage: 51,
            rate: 40,
            accuracy: 55,
            range: 35,
        },
        overall: 37.8,
        icon: 'pistol50',
    },
    pistolmk2: {
        hash: 3219281620,
        name: 'Pistol MK II',
        desc: "Balance, simplicity, precision: nothing keeps the peace like an extended barrel in the other guy's mouth.",
        type: 'Handgun',
        price: 73750,
        clip: 12,
        stats: {
            damage: 38,
            rate: 40,
            accuracy: 40,
            range: 25,
        },
        overall: 30.6,
        icon: 'pistolmk2',
    },
    poolcue: {
        hash: 2484171525,
        name: 'Pool Cue',
        desc: "Ah, there's no sound as satisfying as the crack of a perfect break, especially when it's the other guy's spine.",
        type: 'Melee',
        price: 6250,
        stats: {
            damage: 20,
            rate: 10,
            range: 0,
        },
        overall: 10,
        icon: 'poolcue',
    },
    proxmine: {
        hash: 2874559379,
        name: 'Proximity Mine',
        desc: 'Leave a present for your friends with these motion sensor landmines. Short delay after activation.',
        type: 'Heavy Weapon',
        price: 1000,
        clip: 5,
        stats: {
            damage: 90,
            rate: 10,
            accuracy: 30,
            range: 20,
        },
        overall: 37.5,
        icon: 'proxmine',
    },
    pumpshotgun: {
        hash: 487013001,
        name: 'Pump Shotgun',
        desc: 'Standard shotgun ideal for short-range combat. A high-projectile spread makes up for its lower accuracy at long range.',
        type: 'Shotgun',
        price: 3500,
        clip: 8,
        stats: {
            damage: 67,
            rate: 20,
            accuracy: 30,
            range: 20,
        },
        overall: 29.4,
        icon: 'pumpshotgun',
    },
    pumpshotgunmk2: {
        hash: 1432025498,
        name: 'Pump Shotgun MK II',
        desc: 'Only one thing pumps more action than a pump action: watch out, the recoil is almost as deadly as the shot.',
        type: 'Shotgun',
        price: 82500,
        clip: 8,
        stats: {
            damage: 67,
            rate: 20,
            accuracy: 30,
            range: 20,
        },
        overall: 29.4,
        icon: 'pumpshotgunmk2',
    },
    railgun: {
        hash: 1834241177,
        name: 'Railgun',
        desc: 'Fully-automatic, battery-powered gun, perfect for those looking for a more unusual yet highly-lethal weapon.',
        type: 'Heavy Weapon',
        price: 250000,
        clip: 20,
        stats: {
            damage: 90,
            rate: 25,
            accuracy: 20,
            range: 70,
        },
        overall: 44,
        icon: 'railgun',
    },
    raycarbine: {
        hash: 1198256469,
        name: 'Unholy Hellbringer',
        desc: 'Republican Space Ranger Special. If you want to turn a little green man into little green goo, this is the only American way to do it.',
        type: 'Machine Gun',
        price: 449000,
        clip: 9999,
        stats: {
            damage: 55,
            rate: 65,
            accuracy: 45,
            range: 60,
        },
        overall: 59,
        icon: 'raycarbine',
    },
    rayminigun: {
        hash: 3056410471,
        name: 'Widowmaker',
        desc: "A futuristic Minigun. Republican Space Ranger Special. GO AHEAD, SAY I'M COMPENSATING FOR SOMETHING. I DARE YOU.",
        type: 'Heavy Weapon',
        price: 449000,
        clip: 9999,
        stats: {
            damage: 30,
            rate: 100,
            accuracy: 40,
            range: 55,
        },
        overall: 63,
        icon: 'rayminigun',
    },
    raypistol: {
        hash: 2939590305,
        name: 'Up-n-Atomizer',
        desc: 'A futuristic alien pistol, also known as Raygun. Republican Space Ranger Special, fresh from the galactic war on socialism: no ammo, no mag, just one brutal energy pulse after another.',
        type: 'Handgun',
        price: 399000,
        clip: 9999,
        stats: {
            damage: 80,
            rate: 10,
            accuracy: 10,
            range: 50,
        },
        overall: 32,
        icon: 'raypistol',
    },
    revolver: {
        hash: 3249783761,
        name: 'Heavy Revolver',
        desc: "A handgun with enough stopping power to drop a crazed rhino, and heavy enough to beat it to death if you're out of ammo.",
        type: 'Handgun',
        price: 5900,
        clip: 6,
        stats: {
            damage: 70,
            rate: 20,
            accuracy: 65,
            range: 35,
        },
        overall: 39.2,
        icon: 'revolver',
    },
    revolvermk2: {
        hash: 3415619887,
        name: 'Heavy Revolver MK II',
        desc: "A handgun with enough stopping power to drop a crazed rhino, and heavy enough to beat it to death if you're out of ammo.",
        type: 'Handgun',
        price: 99000,
        clip: 6,
        stats: {
            damage: 75,
            rate: 30,
            accuracy: 65,
            range: 35,
        },
        overall: 42.2,
        icon: 'revolvermk2',
    },
    rpg: {
        hash: 2982836145,
        name: 'RPG',
        desc: 'A portable, shoulder-launched, anti-tank weapon that fires explosive warheads. Very effective for taking down vehicles or large groups of assailants.',
        type: 'Heavy Weapon',
        price: 26250,
        clip: 1,
        stats: {
            damage: 100,
            rate: 5,
            accuracy: 10,
            range: 70,
        },
        overall: 39,
        icon: 'rpg',
    },
    sawnoffshotgun: {
        hash: 2017895192,
        name: 'Sawed-Off Shotgun',
        desc: 'This single-barrel, sawed-off shotgun compensates for its low range and ammo capacity with devastating efficiency in close combat.',
        type: 'Shotgun',
        price: 30000,
        clip: 8,
        stats: {
            damage: 96,
            rate: 20,
            accuracy: 20,
            range: 15,
        },
        overall: 32.2,
        icon: 'sawnoffshotgun',
    },
    smg: {
        hash: 736523883,
        name: 'SMG',
        desc: 'This is known as a good all-around submachine gun. Lightweight with an accurate sight and 30-round magazine capacity.',
        type: 'Machine Gun',
        price: 7500,
        clip: 30,
        stats: {
            damage: 22,
            rate: 55,
            accuracy: 40,
            range: 35,
        },
        overall: 38.4,
        icon: 'smg',
    },
    smgmk2: {
        hash: 2024373456,
        name: 'SMG MK II',
        desc: 'Lightweight, compact, with a rate of fire to die very messily for: turn any confined space into a kill box at the click of a well-oiled trigger.',
        type: 'Machine Gun',
        price: 85500,
        clip: 30,
        stats: {
            damage: 22,
            rate: 55,
            accuracy: 40,
            range: 35,
        },
        overall: 38.4,
        icon: 'smgmk2',
    },
    smokegrenade: {
        hash: 4256991824,
        name: 'Smoke Grenade',
        desc: 'Smoookiinnnn...',
        type: 'Thrown',
        price: 800,
        icon: 'smokegrenade',
    },
    sniperrifle: {
        hash: 100416529,
        name: 'Sniper Rifle',
        desc: 'Standard sniper rifle. Ideal for situations that require accuracy at long range. Limitations include slow reload speed and very low rate of fire.',
        type: 'Sniper Rifle',
        price: 20000,
        clip: 10,
        stats: {
            damage: 96,
            rate: 25,
            accuracy: 70,
            range: 95,
        },
        overall: 59.2,
        icon: 'sniperrifle',
    },
    snowball: {
        hash: 126349499,
        name: 'Snowball',
        desc: 'Be on the lookout and ready to round up your Crew for a friendly snowball fight, but be forewarned, those icy little suckers can pack a wallop',
        type: 'Thrown',
        price: 5,
        clip: 9,
        stats: {
            damage: 1,
            rate: 10,
            accuracy: 10,
            range: 0,
        },
        overall: 5.25,
        icon: 'snowball',
    },
    snspistol: {
        hash: 3218215474,
        name: 'SNS Pistol',
        desc: "Like condoms or hairspray, this fits in your pocket for a night on the town. The price of a bottle at a club, it's half as accurate as a champagne cork, and twice as deadly.",
        type: 'Handgun',
        price: 2750,
        clip: 6,
        stats: {
            damage: 30,
            rate: 40,
            accuracy: 40,
            range: 20,
        },
        overall: 26.6,
        icon: 'snspistol',
    },
    snspistolmk2: {
        hash: 2285322324,
        name: 'SNS Pistol MK II',
        desc: 'The ultimate purse-filler: if you want to make Saturday Night really special, this is your ticket.',
        type: 'Handgun',
        price: 79575,
        clip: 6,
        stats: {
            damage: 30,
            rate: 40,
            accuracy: 40,
            range: 20,
        },
        overall: 26.6,
        icon: 'snspistolmk2',
    },
    specialcarbine: {
        hash: 3231910285,
        name: 'Special Carbine',
        desc: 'Combining accuracy, maneuverability, firepower and low recoil, this is an extremely versatile assault rifle for any combat situation.',
        type: 'Assault Rifle',
        price: 14750,
        clip: 30,
        stats: {
            damage: 34,
            rate: 65,
            accuracy: 55,
            range: 40,
        },
        overall: 46.8,
        icon: 'specialcarbine',
    },
    specialcarbinemk2: {
        hash: 2526821735,
        name: 'Special Carbine MK II',
        desc: 'The jack of all trades just got a serious upgrade: bow to the master.',
        type: 'Assault Rifle',
        price: 135000,
        clip: 30,
        stats: {
            damage: 34,
            rate: 65,
            accuracy: 55,
            range: 40,
        },
        overall: 46.8,
        icon: 'specialcarbinemk2',
    },
    stickybomb: {
        hash: 741814745,
        name: 'Sticky Bomb',
        desc: 'A plastic explosive charge fitted with a remote detonator. Can be thrown and then detonated or attached to a vehicle then detonated.',
        type: 'Thrown',
        price: 60000,
        clip: 25,
        stats: {
            damage: 95,
            rate: 10,
            accuracy: 30,
            range: 10,
        },
        overall: 36.25,
        icon: 'stickybomb',
    },
    stonehatchet: {
        hash: 940833800,
        name: 'Stone Hatchet',
        desc: 'Stone cold killer.',
        type: 'Melee',
        price: 25000,
        stats: {
            damage: 30,
            rate: 15,
            range: 0,
        },
        overall: 15,
        icon: 'stonehatchet',
    },
    stungun: {
        hash: 911657153,
        name: 'Stun Gun',
        desc: 'Fires a projectile that administers a voltage capable of temporarily stunning an assailant. Takes approximately 4 seconds to recharge after firing.',
        type: 'Handgun',
        price: 100,
        stats: {
            damage: 1,
            rate: 10,
            accuracy: 40,
            range: 5,
        },
        overall: 31.2,
        icon: 'stungun',
    },
    switchblade: {
        hash: 3756226112,
        name: 'Switch Blade',
        desc: "From your pocket to hilt-deep in the other guy's ribs in under a second: folding knives will never go out of style.",
        type: 'Melee',
        price: 1950,
        stats: {
            damage: 15,
            rate: 20,
            range: 0,
        },
        overall: 11.67,
        icon: 'switchblade',
    },
    unarmed: {
        hash: 2725352035,
        name: 'unarmed',
        icon: 'unarmed',
    },
    vintagepistol: {
        hash: 137902532,
        name: 'Vintage Pistol',
        desc: 'What you really need is a more recognisable gun. Stand out from the crowd at an armed robbery with this engraved pistol.',
        type: 'Handgun',
        price: 3450,
        stats: {
            damage: 35,
            rate: 40,
            accuracy: 40,
            range: 25,
        },
        overall: 29.2,
        icon: 'vintagepistol',
    },
};

/**
 * Get a weapon hash by its string name.
 * @export
 * @param {string} name
 * @return {*}  {(number | null)}
 */
export function getWeaponByName(name: string): Weapon | null {
    return WeaponList[name];
}

/**
 * Get all the weapons in the game.
 * @returns An array of all the weapons in the WeaponList.
 */
export function getWeaponList(): Array<Weapon> {
    return Object.values(WeaponList);
}
