// @ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED. USE 'AthenaConfig.json' TO ADD PLUGINS

import { shallowRef } from 'vue';
import Atm from '../../core-atm/webview/Atm.vue';
import CharacterCreator from '../../core-character-creator/webview/CharacterCreator.vue';
import CharacterSelect from '../../core-character-select/webview/CharacterSelect.vue';
import Clothing from '../../core-clothing/webview/Clothing.vue';
import Dealership from '../../core-dealership/webview/Dealership.vue';
import Factions from '../../core-factions/webview/Factions.vue';
import Garage from '../../core-garage/webview/Garage.vue';
import Hud from '../../core-hud/webview/Hud.vue';
import PaintShop from '../../core-paintshop/webview/PaintShop.vue';

export const PLUGIN_IMPORTS = {
    Atm: shallowRef(Atm),
    CharacterCreator: shallowRef(CharacterCreator),
    CharacterSelect: shallowRef(CharacterSelect),
    Clothing: shallowRef(Clothing),
    Dealership: shallowRef(Dealership),
    Factions: shallowRef(Factions),
    Garage: shallowRef(Garage),
    Hud: shallowRef(Hud),
    PaintShop: shallowRef(PaintShop),
};

// THIS FILE IS AUTOMATICALLY GENERATED. USE 'AthenaConfig.json' TO ADD PLUGINS
