// THIS FILE IS AUTOMATICALLY GENERATED. USE 'AthenaConfig.json' TO ADD PLUGINS

import { PluginSystem } from '../../../server/systems/plugins';

import '../../commands-moderator/server/index';
import '../../commands-roleplay/server/index';
import '../../core-atm/server/index';
import '../../core-character-creator/server/index';
import '../../core-character-select/server/index';
import '../../core-clothing/server/index';
import '../../core-console-cmds/server/index';
import '../../core-cuffs/server/index';
import '../../core-dealership/server/index';
import '../../core-factions/server/index';
import '../../core-fuel-stations/server/index';
import '../../core-fuel/server/index';
import '../../core-garage/server/index';
import '../../core-interior/server/index';
import '../../core-items/server/index';
import '../../core-nametags/server/index';
import '../../core-paintshop/server/index';
import '../../core-vitals/server/index';
import '../../core-voice/server/index';
import '../../example-agenda/server/index';
import '../../job-mule-delivery/server/index';
import '../../job-pizza-delivery/server/index';

PluginSystem.init();

// THIS FILE IS AUTOMATICALLY GENERATED. USE 'AthenaConfig.json' TO ADD PLUGINS
