export const EquipmentSlots: Array<{ name: string; slot: number; displayOrder: number }> = [
    { name: 'HAT', slot: 0, displayOrder: 0 },
    { name: 'GLASSES', slot: 5, displayOrder: 1 },
    { name: 'MASK', slot: 1, displayOrder: 2 },
    { name: 'EARS', slot: 6, displayOrder: 3 },
    { name: 'SHIRT', slot: 2, displayOrder: 4 },
    { name: 'ACCESSORY', slot: 11, displayOrder: 5 },
    { name: 'BAG', slot: 7, displayOrder: 6 },
    { name: 'PANTS', slot: 3, displayOrder: 7 },
    { name: 'WATCH', slot: 9, displayOrder: 8 },
    { name: 'FEET', slot: 4, displayOrder: 9 },
    { name: 'BRACELET', slot: 10, displayOrder: 10 },
    { name: 'ARMOUR', slot: 8, displayOrder: 11 },
    { name: 'OUTFIT', slot: 12, displayOrder: 12 },
];
