export default [
    {
        name: 'LABEL_HAT',
        ids: [0],
        drawables: [0],
        textures: [0],
        maxDrawables: [5],
        maxTextures: [5],
        isProp: true,
    },
    {
        name: 'LABEL_MASK',
        ids: [1],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: false,
    },
    {
        name: 'LABEL_SHIRT',
        addonLocales: ['LABEL_TOP', 'LABEL_UNDERSHIRT', 'LABEL_TORSO'],
        ids: [11, 8, 3],
        drawables: [0, 0, 0],
        textures: [0, 0, 0],
        maxDrawables: [0, 0, 0],
        maxTextures: [0, 0, 0],
        isProp: false,
    },
    {
        name: 'LABEL_BOTTOMS',
        ids: [4],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: false,
    },
    {
        name: 'LABEL_SHOES',
        ids: [6],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: false,
    },
    {
        name: 'LABEL_GLASSES',
        ids: [1],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: true,
    },
    {
        name: 'LABEL_EARRINGS',
        ids: [2],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: true,
    },
    {
        name: 'LABEL_BAG',
        ids: [5],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: false,
    },
    {
        name: 'LABEL_ARMOUR',
        ids: [9],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: false,
    },
    {
        name: 'LABEL_WATCH',
        ids: [6],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: true,
    },
    {
        name: 'LABEL_BRACELET',
        ids: [7],
        drawables: [0],
        textures: [0],
        maxDrawables: [0],
        maxTextures: [0],
        isProp: true,
    },
];
