const structureLabels = [
    'Nose Width',
    'Nose Height',
    'Nose Length',
    'Nose Bridge',
    'Nose Tip',
    'Nose Bridge Shaft',
    'Brow Height',
    'Brow Width',
    'Cheekbone Height',
    'Cheekbone Width',
    'Cheek Width',
    'Eyelids',
    'Lips',
    'Jaw Width',
    'Jaw Height',
    'Chin Length',
    'Chin Position',
    'Chin Width',
    'Chin Shape',
    'Neck Width'
];
