import '../systems/account.js';
import '../systems/adminControl.js';
import '../systems/global.js';
import '../systems/identifier.js';
import '../systems/inventory/clothing.js';
import '../systems/inventory/config.js';
import '../systems/inventory/crafting.js';
import '../systems/inventory/drops.js';
import '../systems/inventory/effects.js';
import '../systems/inventory/factory.js';
import '../systems/inventory/manager.js';
import '../systems/inventory/slot.js';
import '../systems/inventory/weapons.js';
import '../systems/inventory/weight.js';
import '../systems/job/events.js';
import '../systems/job/instance.js';
import '../systems/job/system.js';
import '../systems/job/triggers.js';
import '../systems/job/verify.js';
import '../systems/jobTrigger.js';
import '../systems/messenger/messaging.js';
import '../systems/plugins.js';
import '../systems/tick.js';

// Defaults Systems - With Toggleable Configs
// HEY YOU! IF YOU WANNA DISABLE SOMETHING. DO IT THROUGH A PLUGIN.
// Athena.systems.defaults.x.disable()
import '../systems/defaults/ammo.js';
import '../systems/defaults/clothingCrafting.js';
import '../systems/defaults/death.js';
import '../systems/defaults/displayId.js';
import '../systems/defaults/inventorySync.js';
import '../systems/defaults/time.js';
import '../systems/defaults/toolbar.js';
import '../systems/defaults/vehiclesDespawnOnDestroy.js';
import '../systems/defaults/vehiclesDespawnOnLeave.js';
import '../systems/defaults/vehiclesSpawnOnJoin.js';
import '../systems/defaults/weaponItems.js';
import '../systems/defaults/weather.js';
