import '../systems/account';
import '../systems/adminControl';
import '../systems/global';
import '../systems/identifier';
import '../systems/inventory/clothing';
import '../systems/inventory/config';
import '../systems/inventory/crafting';
import '../systems/inventory/drops';
import '../systems/inventory/effects';
import '../systems/inventory/factory';
import '../systems/inventory/manager';
import '../systems/inventory/slot';
import '../systems/inventory/weapons';
import '../systems/inventory/weight';
import '../systems/job/events';
import '../systems/job/instance';
import '../systems/job/system';
import '../systems/job/triggers';
import '../systems/job/verify';
import '../systems/jobTrigger';
import '../systems/messenger/messaging';
import '../systems/plugins';
import '../systems/streamer';
import '../systems/tick';

// Defaults Systems - With Toggleable Configs
// HEY YOU! IF YOU WANNA DISABLE SOMETHING. DO IT THROUGH A PLUGIN.
// Athena.systems.defaults.x.disable()
import '../systems/defaults/ammo';
import '../systems/defaults/clothingCrafting';
import '../systems/defaults/death';
import '../systems/defaults/displayId';
import '../systems/defaults/inventorySync';
import '../systems/defaults/time';
import '../systems/defaults/toolbar';
import '../systems/defaults/vehiclesDespawnOnDestroy';
import '../systems/defaults/vehiclesDespawnOnLeave';
import '../systems/defaults/vehiclesSpawnOnJoin';
import '../systems/defaults/weaponItems';
import '../systems/defaults/weather';
