import BadgeStyle from "../enums/BadgeStyle";
import ItemsCollection from "../modules/ItemsCollection";
import ListItem from "../modules/ListItem";
import ResText from "../modules/ResText";
import Sprite from "../modules/Sprite";
import UIMenuItem from "./UIMenuItem";
export default class UIMenuListItem extends UIMenuItem {
    ScrollingEnabled: boolean;
    HoldTimeBeforeScroll: number;
    protected _itemText: ResText;
    protected _arrowLeft: Sprite;
    protected _arrowRight: Sprite;
    private _currentOffset;
    private _itemsCollection;
    get Collection(): ListItem[];
    set Collection(v: ListItem[]);
    set SelectedItem(v: ListItem);
    get SelectedItem(): ListItem;
    get SelectedValue(): any;
    protected _index: number;
    get Index(): number;
    set Index(value: number);
    constructor(text: string, description?: string, collection?: ItemsCollection, startIndex?: number, data?: any);
    setCollection(collection: ItemsCollection): void;
    setCollectionItem(index: number, item: ListItem | string, resetSelection?: boolean): void;
    SetVerticalPosition(y: number): void;
    SetRightLabel(text: string): this;
    SetRightBadge(badge: BadgeStyle): this;
    Draw(): void;
}
