export const DefaultInventory = [
    {
        dbName: 'burger',
        quantity: 6,
        data: {
            health: 5,
        },
        slot: 0,
        totalWeight: 6,
    },
    {
        dbName: 'fishingrod',
        quantity: 1,
        data: {
            model: 'prop_fishing_rod_01',
            pos: {
                x: -6.938893903907228e-18,
                y: -0.039999999999999994,
                z: 0.16,
            },
            rot: {
                x: -6.938893903907228e-18,
                y: -0.32,
                z: 0.18,
            },
            bone: 58,
        },
        slot: 1,
        totalWeight: null,
        isEquipped: false,
        model: 'prop_fishing_rod_01',
    },
    {
        dbName: 'salmon',
        quantity: 1,
        data: {},
        slot: 2,
        totalWeight: 1,
    },
    {
        dbName: 'sardine',
        quantity: 3,
        data: {},
        slot: 3,
        totalWeight: 3,
    },
    {
        dbName: 'cod',
        quantity: 1,
        data: {},
        slot: 4,
        totalWeight: 1,
    },
    {
        dbName: 'goldfish',
        quantity: 1,
        data: {},
        slot: 5,
        totalWeight: 1,
        isEquipped: false,
        model: 'xm3_prop_xm3_package_01a',
    },
    {
        dbName: 'clothing',
        quantity: 1,
        data: {
            sex: 1,
            components: [
                {
                    id: 8,
                    drawable: 1,
                    texture: 0,
                    palette: 0,
                    dlc: 0,
                    isProp: false,
                },
                {
                    id: 6,
                    drawable: 1,
                    texture: 0,
                    palette: 0,
                    dlc: 0,
                    isProp: false,
                },
                {
                    id: 11,
                    drawable: 1,
                    texture: 0,
                    palette: 0,
                    dlc: 0,
                    isProp: false,
                },
            ],
        },
        slot: 6,
        totalWeight: 1,
        isEquipped: true,
    },
];
