// THIS FILE IS AUTOMATICALLY GENERATED. USE 'AthenaConfig.json' TO ADD PLUGINS

import '../../core-atm/client/index';
import '../../core-character-creator/client/index';
import '../../core-character-select/client/index';
import '../../core-clothing/client/index';
import '../../core-console-cmds/client/index';
import '../../core-dealership/client/index';
import '../../core-garage/client/index';
import '../../core-hud/client/index';
import '../../core-interior/client/index';
import '../../core-nametags/client/index';
import '../../core-paintshop/client/index';
import '../../example-agenda/client/index';

// THIS FILE IS AUTOMATICALLY GENERATED. USE 'AthenaConfig.json' TO ADD PLUGINS
