export default [
    {
        min: 0,
        max: 74,
        increment: 1,
        id: 4,
        opacity: 0,
        color1: 0,
        color2: 0,
        value: 0,
    },
    {
        min: 0,
        max: 6,
        increment: 1,
        id: 5,
        opacity: 0,
        color1: 0,
        value: 0,
    },
    {
        min: 0,
        max: 9,
        increment: 1,
        id: 8,
        opacity: 0,
        color1: 0,
        value: 0,
    },
];
