export default [
    {
        min: 0,
        max: 23,
        increment: 1,
        id: 0,
        opacity: 0,
        value: 0,
    },
    {
        min: 0,
        max: 14,
        increment: 1,
        id: 3,
        opacity: 0,
        value: 0,
    },
    {
        min: 0,
        max: 11,
        increment: 1,
        id: 6,
        opacity: 0,
        value: 0,
    },
    {
        min: 0,
        max: 10,
        increment: 1,
        id: 7,
        opacity: 0,
        value: 0,
    },
    {
        min: 0,
        max: 17,
        increment: 1,
        id: 9,
        opacity: 0,
        value: 0,
    },
    {
        min: 0,
        max: 11,
        increment: 1,
        id: 11,
        opacity: 0,
        value: 0,
    },
];
