export const MalePresets = [
    {
        faceMother: 0,
        faceFather: 0,
        skinMother: 0,
        skinFather: 0,
        skinMix: 0.5,
        faceMix: 0.5,
        hair: 4,
        hairColor1: 1,
        hairColor2: 5,
    },
    {
        sex: 1,
        faceFather: 3,
        faceMother: 0,
        skinFather: 3,
        skinMother: 4,
        faceMix: 0.6,
        skinMix: 0.5,
        hair: 28,
        hairColor1: 0,
        hairColor2: 5,
        facialHair: 14,
        facialHairColor1: 0,
        facialHairOpacity: 0.6,
        eyes: 5,
    },
    {
        sex: 1,
        faceFather: 18,
        faceMother: 0,
        skinFather: 3,
        skinMother: 4,
        faceMix: 0.6,
        skinMix: 0,
        hair: 30,
        hairColor1: 1,
        hairColor2: 5,
        facialHair: 16,
        facialHairColor1: 0,
        facialHairOpacity: 0.9,
        eyebrows: 0,
        eyebrowsOpacity: 1,
        eyebrowsColor1: 0,
        eyes: 5,
    },
    {
        sex: 1,
        faceFather: 0,
        faceMother: 42,
        skinFather: 0,
        skinMother: 27,
        faceMix: 0.5,
        skinMix: 0.2,
        hair: 54,
        hairColor1: 1,
        hairColor2: 5,
        facialHair: 4,
        facialHairColor1: 0,
        facialHairOpacity: 1,
        eyebrows: 0,
        eyebrowsOpacity: 1,
        eyebrowsColor1: 0,
        eyes: 5,
    },
    {
        sex: 1,
        faceFather: 44,
        faceMother: 38,
        skinFather: 16,
        skinMother: 23,
        faceMix: 0.5,
        skinMix: 0.1,
        hair: 68,
        hairColor1: 5,
        hairColor2: 8,
        facialHair: 8,
        facialHairColor1: 5,
        facialHairOpacity: 1,
        eyebrows: 0,
        eyebrowsOpacity: 1,
        eyebrowsColor1: 4,
        eyes: 3,
    },
    {
        sex: 1,
        faceFather: 10,
        faceMother: 2,
        skinFather: 35,
        skinMother: 27,
        faceMix: 0.5,
        skinMix: 0.1,
        hair: 53,
        hairColor1: 3,
        hairColor2: 6,
        facialHair: 29,
        facialHairColor1: 3,
        facialHairOpacity: 1,
        eyebrows: 0,
        eyebrowsOpacity: 1,
        eyebrowsColor1: 4,
        eyes: 1,
    },
];

export const FemalePresets = [
    {
        faceMother: 45,
        faceFather: 45,
        skinMother: 45,
        skinFather: 45,
        skinMix: 0.5,
        faceMix: 0.5,
        hair: 4,
        hairColor1: 1,
        hairColor2: 5,
    },
    {
        sex: 0,
        faceFather: 22,
        faceMother: 25,
        skinFather: 36,
        skinMother: 45,
        faceMix: 0.5,
        skinMix: 0.2,
        hair: 20,
        hairColor1: 3,
        hairColor2: 2,
    },
    {
        sex: 0,
        faceFather: 21,
        faceMother: 25,
        skinFather: 36,
        skinMother: 41,
        faceMix: 0.8,
        skinMix: 1,
        hair: 34,
        hairColor1: 3,
        hairColor2: 2,
        eyes: 3,
    },
    {
        sex: 0,
        faceFather: 27,
        faceMother: 45,
        skinFather: 36,
        skinMother: 45,
        faceMix: 0.3,
        skinMix: 0.9,
        hair: 40,
        hairColor1: 3,
        hairColor2: 40,
    },
    {
        sex: 0,
        faceFather: 33,
        faceMother: 45,
        skinFather: 30,
        skinMother: 45,
        faceMix: 0.3,
        skinMix: 0.5,
        hair: 4,
        hairColor1: 13,
        hairColor2: 10,
        eyes: 2,
    },
    {
        sex: 0,
        faceFather: 33,
        faceMother: 30,
        skinFather: 14,
        skinMother: 45,
        faceMix: 0.3,
        skinMix: 0.3,
        hair: 43,
        hairColor1: 4,
        hairColor2: 5,
        eyes: 5,
    },
];
